# Generated by Django 3.1.5 on 2021-02-11 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_menu', models.CharField(max_length=100)),
                ('img_menu', models.ImageField(blank=True, null=True, upload_to='media')),
                ('cat_menu', models.CharField(max_length=100)),
                ('price_menu', models.DecimalField(decimal_places=0, max_digits=100)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='MenuOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=100, null=True)),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoran.menumodel')),
                ('price_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priceproduct', to='restoran.menumodel')),
            ],
        ),
    ]
