# Generated by Django 3.1.5 on 2021-02-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0002_menuorder_order_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuorder',
            name='table_customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuorder',
            name='time_ordered',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
