# Generated by Django 3.1.5 on 2021-02-13 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restoran', '0003_auto_20210213_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuorder',
            name='table_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tablecustomer', to=settings.AUTH_USER_MODEL),
        ),
    ]
